#ifndef _ANGLETRACKER_H_
#define _ANGLETRACKER_H_

#include <cmath>       // For std::abs
#include <chrono>      // For std::chrono::steady_clock
#include <deque>       // For std::deque
#include <algorithm>   // For std::max

/*
 * AngleTracker Class (generated by GitHub Copilot)
 * ------------------
 * The AngleTracker class is designed to track and analyze a series of numerical values (angles) over time.
 * It maintains a running average of the values and keeps track of the most recent 10 values along with their
 * timestamps. The class provides the following functionality:
 *
 * - Add a new value to the tracker (only if it exceeds the current average).
 * - Automatically remove values older than 5 seconds from the tracker.
 * - Retrieve the maximum value among the last 10 values, with an optional adjustment.
 * - Retrieve the running average of the tracked values.
 *
 * This class is useful for applications that require real-time tracking and analysis of numerical data,
 * such as motion tracking, robotics, or sensor data processing.
 */

class AngleTracker {
private:
    struct DataPoint {
        float value; // The value of the data
        std::chrono::steady_clock::time_point timestamp; // The time the data was added
    };

    std::deque<DataPoint> last_10_numbers; // Stores the last 10 valid numbers with timestamps
    float average; // Running average of valid numbers

public:
    AngleTracker();
    void add_number(float number);
    float get_average() {return average;}
    float get_max_value(int epsilon);

private:
    void remove_old_elements();
    void update_average(float number);
};

#endif